# ./manifests/inventory-app/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-app
  labels:
    app: inventory-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-app
  template:
    metadata:
      labels:
        app: inventory-app
    spec:
      containers:
        - name: inventory-app
          image: mouhameddiouf01/inventory-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: INVENTORY_APP_PORT
              value: "8080"
            - name: INVENTORY_DB_USER
              valueFrom:
                secretKeyRef:
                  name: inventory-db-secret
                  key: username
            - name: INVENTORY_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: inventory-db-secret
                  key: password
            - name: INVENTORY_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: inventory-db-secret
                  key: dbname
            - name: INVENTORY_DB_HOST # Ajoutez cette variable
              value: "inventory-db"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10