apiVersion: v1
kind: Secret
metadata:
  name: billing-db-secret
type: Opaque
data:
  username: dXNlcjAx          # user01
  password: cGFzc3dvcmQ=      # password
  dbname: YmlsbGluZ19kYg==    # billing_db
