apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
data:
  username: cmFiYml0          # rabbit
  password: cGFzc3dvcmQ=      # password
  queue: YmlsbGluZ19xdWV1ZQ== # billing_queue
