# ./manifests/billing-app/statefulset.yaml

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: billing-app
spec:
  serviceName: billing-app
  replicas: 1
  selector:
    matchLabels:
      app: billing-app
  template:
    metadata:
      labels:
        app: billing-app
    spec:
      initContainers:
        - name: wait-for-dependencies
          image: busybox:1.28
          command:
            - sh
            - -c
            - |
              until nslookup billing-db.default.svc.cluster.local && echo "billing-db OK"; do echo waiting for billing-db; sleep 5; done;
              until nslookup rabbitmq.default.svc.cluster.local && echo "rabbitmq OK"; do echo waiting for rabbitmq; sleep 5; done;
              sleep 10
      containers:
        - name: billing-app
          image: mouhameddiouf01/billing-app:latest
          ports:
            - containerPort: 5000
          env:
            - name: BILLING_DB_USER
              valueFrom:
                secretKeyRef:
                  name: billing-db-secret
                  key: username
            - name: BILLING_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: billing-db-secret
                  key: password
            - name: BILLING_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: billing-db-secret
                  key: dbname
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: password
            - name: RABBITMQ_QUEUE
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: queue
