# ./manifests/billing-app/statefulset.yaml

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: billing-app
spec:
  serviceName: billing-app
  replicas: 1
  selector:
    matchLabels:
      app: billing-app
  template:
    metadata:
      labels:
        app: billing-app
    spec:
      # initContainers:
      #   - name: wait-for-services
      #     image: busybox
      #     command: ['sh', '-c', 'nslookup billing-db && nslookup rabbitmq && sleep 2']
      #     env: []
      containers:
        - name: billing-app
          image: mouhameddiouf01/billing-app:latest
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args: ["-c", "env && sleep 3600"]
          ports:
            - containerPort: 5000
          env:
            - name: BILLING_DB_USER
              valueFrom:
                secretKeyRef:
                  name: billing-db-secret
                  key: username
            - name: BILLING_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: billing-db-secret
                  key: password
            - name: BILLING_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: billing-db-secret
                  key: dbname
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: password
            - name: RABBITMQ_QUEUE
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: queue