# ./manifests/secrets/billing-db-secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: billing-db-secret
type: Opaque
data:
  username: dXNlcjAx          # user01
  password: cGFzc3dvcmQ=      # password
  dbname: YmlsbGluZ19kYg==    # billing_db

# apiVersion: v1
# kind: Secret
# metadata:
#   name: billing-db-secret
# type: Opaque
# stringData:
#   username: user01
#   password: password
#   dbname: billing_db
