apiVersion: v1
kind: Secret
metadata:
  name: inventory-db-secret
type: Opaque
data:
  username: dXNlcjAx          # user01
  password: cG9zdGdyZXM=      # postgres
  dbname: aW52ZW50b3J5X2Ri    # inventory_db
