# ./manifests/secrets/inventory-db-secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: inventory-db-secret
type: Opaque
data:
  username: dXNlcjAx
  password: cG9zdGdyZXM=
  dbname: aW52ZW50b3J5X2Ri
