# ./manifests/secrets/rabbitmq-secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
data:
  username: cmFiYml0
  password: cGFzc3dvcmQ=
  queue: YmlsbGluZ19xdWV1ZQ==
